// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _knn_HH_
#define _knn_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "knn_distances_0.h"
#include "knn_distances_1.h"
#include "knn_freq.h"
#include "knn_AXILiteS_s_axi.h"

namespace ap_rtl {

template<unsigned int C_S_AXI_AXILITES_ADDR_WIDTH = 21,
         unsigned int C_S_AXI_AXILITES_DATA_WIDTH = 32>
struct knn : public sc_module {
    // Port declarations 20
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst_n;
    sc_in< sc_logic > s_axi_AXILiteS_AWVALID;
    sc_out< sc_logic > s_axi_AXILiteS_AWREADY;
    sc_in< sc_uint<C_S_AXI_AXILITES_ADDR_WIDTH> > s_axi_AXILiteS_AWADDR;
    sc_in< sc_logic > s_axi_AXILiteS_WVALID;
    sc_out< sc_logic > s_axi_AXILiteS_WREADY;
    sc_in< sc_uint<C_S_AXI_AXILITES_DATA_WIDTH> > s_axi_AXILiteS_WDATA;
    sc_in< sc_uint<C_S_AXI_AXILITES_DATA_WIDTH/8> > s_axi_AXILiteS_WSTRB;
    sc_in< sc_logic > s_axi_AXILiteS_ARVALID;
    sc_out< sc_logic > s_axi_AXILiteS_ARREADY;
    sc_in< sc_uint<C_S_AXI_AXILITES_ADDR_WIDTH> > s_axi_AXILiteS_ARADDR;
    sc_out< sc_logic > s_axi_AXILiteS_RVALID;
    sc_in< sc_logic > s_axi_AXILiteS_RREADY;
    sc_out< sc_uint<C_S_AXI_AXILITES_DATA_WIDTH> > s_axi_AXILiteS_RDATA;
    sc_out< sc_lv<2> > s_axi_AXILiteS_RRESP;
    sc_out< sc_logic > s_axi_AXILiteS_BVALID;
    sc_in< sc_logic > s_axi_AXILiteS_BREADY;
    sc_out< sc_lv<2> > s_axi_AXILiteS_BRESP;
    sc_out< sc_logic > interrupt;
    sc_signal< sc_logic > ap_var_for_const0;


    // Module declarations
    knn(sc_module_name name);
    SC_HAS_PROCESS(knn);

    ~knn();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    knn_AXILiteS_s_axi<C_S_AXI_AXILITES_ADDR_WIDTH,C_S_AXI_AXILITES_DATA_WIDTH>* knn_AXILiteS_s_axi_U;
    knn_distances_0* distances_0_U;
    knn_distances_1* distances_1_U;
    knn_freq* freq_U;
    sc_signal< sc_logic > ap_rst_n_inv;
    sc_signal< sc_logic > ap_start;
    sc_signal< sc_logic > ap_done;
    sc_signal< sc_logic > ap_idle;
    sc_signal< sc_lv<12> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_logic > ap_ready;
    sc_signal< sc_lv<404> > input_V;
    sc_signal< sc_lv<13> > train_samples_V_address0;
    sc_signal< sc_logic > train_samples_V_ce0;
    sc_signal< sc_lv<404> > train_samples_V_q0;
    sc_signal< sc_lv<1> > output_V;
    sc_signal< sc_logic > output_V_ap_vld;
    sc_signal< sc_lv<4> > test_label_V_fu_355_p1;
    sc_signal< sc_lv<4> > test_label_V_reg_585;
    sc_signal< sc_lv<400> > test_data_V_reg_590;
    sc_signal< sc_lv<3> > i_fu_375_p2;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<13> > i_4_fu_393_p2;
    sc_signal< sc_lv<13> > i_4_reg_606;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<1> > icmp_ln32_fu_387_p2;
    sc_signal< sc_lv<404> > p_Val2_1_reg_616;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_lv<400> > p_Val2_3_reg_621;
    sc_signal< sc_lv<9> > i_2_fu_424_p2;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_lv<16> > select_ln83_fu_456_p3;
    sc_signal< sc_lv<1> > icmp_ln82_fu_418_p2;
    sc_signal< sc_lv<4> > curr_label_V_fu_464_p1;
    sc_signal< sc_lv<3> > j_fu_473_p2;
    sc_signal< sc_lv<3> > j_reg_647;
    sc_signal< sc_logic > ap_CS_fsm_state6;
    sc_signal< sc_lv<64> > zext_ln39_fu_479_p1;
    sc_signal< sc_lv<64> > zext_ln39_reg_652;
    sc_signal< sc_lv<1> > icmp_ln36_fu_467_p2;
    sc_signal< sc_lv<3> > distances_0_addr_1_reg_657;
    sc_signal< sc_lv<16> > distances_0_q0;
    sc_signal< sc_lv<16> > curr_dist_1_reg_662;
    sc_signal< sc_logic > ap_CS_fsm_state7;
    sc_signal< sc_lv<1> > icmp_ln39_fu_484_p2;
    sc_signal< sc_lv<1> > icmp_ln39_reg_667;
    sc_signal< sc_lv<4> > i_1_fu_506_p2;
    sc_signal< sc_logic > ap_CS_fsm_state9;
    sc_signal< sc_lv<3> > i_3_fu_523_p2;
    sc_signal< sc_lv<3> > i_3_reg_687;
    sc_signal< sc_logic > ap_CS_fsm_state10;
    sc_signal< sc_lv<1> > icmp_ln62_fu_517_p2;
    sc_signal< sc_lv<16> > sext_ln64_fu_544_p1;
    sc_signal< sc_lv<16> > sext_ln64_reg_697;
    sc_signal< sc_logic > ap_CS_fsm_state11;
    sc_signal< sc_lv<4> > freq_addr_1_reg_702;
    sc_signal< sc_lv<32> > select_ln66_fu_569_p3;
    sc_signal< sc_logic > ap_CS_fsm_state12;
    sc_signal< sc_lv<32> > select_ln66_1_fu_577_p3;
    sc_signal< sc_lv<3> > distances_0_address0;
    sc_signal< sc_logic > distances_0_ce0;
    sc_signal< sc_logic > distances_0_we0;
    sc_signal< sc_lv<16> > distances_0_d0;
    sc_signal< sc_lv<3> > distances_1_address0;
    sc_signal< sc_logic > distances_1_ce0;
    sc_signal< sc_logic > distances_1_we0;
    sc_signal< sc_lv<5> > distances_1_d0;
    sc_signal< sc_lv<5> > distances_1_q0;
    sc_signal< sc_lv<4> > freq_address0;
    sc_signal< sc_logic > freq_ce0;
    sc_signal< sc_logic > freq_we0;
    sc_signal< sc_lv<32> > freq_d0;
    sc_signal< sc_lv<32> > freq_q0;
    sc_signal< sc_lv<3> > i_0_reg_207;
    sc_signal< sc_lv<1> > icmp_ln26_fu_369_p2;
    sc_signal< sc_lv<13> > i1_0_reg_218;
    sc_signal< sc_lv<16> > curr_dist_reg_229;
    sc_signal< sc_lv<9> > bvh_d_index_reg_241;
    sc_signal< sc_lv<4> > temp2_V_reg_252;
    sc_signal< sc_lv<4> > ap_phi_mux_temp2_V_be_phi_fu_289_p4;
    sc_signal< sc_logic > ap_CS_fsm_state8;
    sc_signal< sc_lv<16> > temp1_reg_262;
    sc_signal< sc_lv<16> > ap_phi_mux_temp1_be_phi_fu_301_p4;
    sc_signal< sc_lv<3> > j_0_reg_274;
    sc_signal< sc_lv<4> > curr_label_V_1_fu_495_p1;
    sc_signal< sc_lv<4> > temp2_V_be_reg_285;
    sc_signal< sc_lv<16> > temp1_be_reg_297;
    sc_signal< sc_lv<4> > i2_0_reg_309;
    sc_signal< sc_lv<1> > icmp_ln57_fu_500_p2;
    sc_signal< sc_lv<32> > max_freq_0_reg_320;
    sc_signal< sc_lv<32> > most_freq_0_reg_332;
    sc_signal< sc_lv<3> > i3_0_reg_344;
    sc_signal< sc_lv<64> > zext_ln27_fu_381_p1;
    sc_signal< sc_lv<64> > zext_ln34_fu_399_p1;
    sc_signal< sc_lv<64> > zext_ln58_fu_512_p1;
    sc_signal< sc_lv<64> > zext_ln64_fu_529_p1;
    sc_signal< sc_lv<64> > zext_ln65_fu_548_p1;
    sc_signal< sc_lv<5> > zext_ln45_fu_490_p1;
    sc_signal< sc_lv<32> > max_freq_fu_556_p2;
    sc_signal< sc_lv<32> > zext_ln82_fu_414_p1;
    sc_signal< sc_lv<1> > p_Result_s_fu_430_p3;
    sc_signal< sc_lv<1> > p_Result_1_fu_437_p3;
    sc_signal< sc_lv<1> > xor_ln968_fu_444_p2;
    sc_signal< sc_lv<16> > distance_fu_450_p2;
    sc_signal< sc_lv<32> > zext_ln73_fu_534_p1;
    sc_signal< sc_lv<1> > icmp_ln66_fu_563_p2;
    sc_signal< sc_lv<32> > most_freq_fu_553_p1;
    sc_signal< sc_lv<12> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<12> ap_ST_fsm_state1;
    static const sc_lv<12> ap_ST_fsm_state2;
    static const sc_lv<12> ap_ST_fsm_state3;
    static const sc_lv<12> ap_ST_fsm_state4;
    static const sc_lv<12> ap_ST_fsm_state5;
    static const sc_lv<12> ap_ST_fsm_state6;
    static const sc_lv<12> ap_ST_fsm_state7;
    static const sc_lv<12> ap_ST_fsm_state8;
    static const sc_lv<12> ap_ST_fsm_state9;
    static const sc_lv<12> ap_ST_fsm_state10;
    static const sc_lv<12> ap_ST_fsm_state11;
    static const sc_lv<12> ap_ST_fsm_state12;
    static const sc_lv<32> ap_const_lv32_0;
    static const int C_S_AXI_DATA_WIDTH;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<32> ap_const_lv32_9;
    static const sc_lv<32> ap_const_lv32_A;
    static const sc_lv<32> ap_const_lv32_B;
    static const sc_lv<3> ap_const_lv3_0;
    static const sc_lv<13> ap_const_lv13_0;
    static const sc_lv<16> ap_const_lv16_0;
    static const sc_lv<9> ap_const_lv9_0;
    static const sc_lv<32> ap_const_lv32_7;
    static const sc_lv<4> ap_const_lv4_0;
    static const sc_lv<32> ap_const_lv32_FFFFFFFF;
    static const sc_lv<16> ap_const_lv16_320;
    static const sc_lv<5> ap_const_lv5_1F;
    static const sc_lv<32> ap_const_lv32_193;
    static const sc_lv<3> ap_const_lv3_5;
    static const sc_lv<3> ap_const_lv3_1;
    static const sc_lv<13> ap_const_lv13_1770;
    static const sc_lv<13> ap_const_lv13_1;
    static const sc_lv<9> ap_const_lv9_190;
    static const sc_lv<9> ap_const_lv9_1;
    static const sc_lv<16> ap_const_lv16_1;
    static const sc_lv<4> ap_const_lv4_A;
    static const sc_lv<4> ap_const_lv4_1;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state10();
    void thread_ap_CS_fsm_state11();
    void thread_ap_CS_fsm_state12();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state5();
    void thread_ap_CS_fsm_state6();
    void thread_ap_CS_fsm_state7();
    void thread_ap_CS_fsm_state8();
    void thread_ap_CS_fsm_state9();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_phi_mux_temp1_be_phi_fu_301_p4();
    void thread_ap_phi_mux_temp2_V_be_phi_fu_289_p4();
    void thread_ap_ready();
    void thread_ap_rst_n_inv();
    void thread_curr_label_V_1_fu_495_p1();
    void thread_curr_label_V_fu_464_p1();
    void thread_distance_fu_450_p2();
    void thread_distances_0_address0();
    void thread_distances_0_ce0();
    void thread_distances_0_d0();
    void thread_distances_0_we0();
    void thread_distances_1_address0();
    void thread_distances_1_ce0();
    void thread_distances_1_d0();
    void thread_distances_1_we0();
    void thread_freq_address0();
    void thread_freq_ce0();
    void thread_freq_d0();
    void thread_freq_we0();
    void thread_i_1_fu_506_p2();
    void thread_i_2_fu_424_p2();
    void thread_i_3_fu_523_p2();
    void thread_i_4_fu_393_p2();
    void thread_i_fu_375_p2();
    void thread_icmp_ln26_fu_369_p2();
    void thread_icmp_ln32_fu_387_p2();
    void thread_icmp_ln36_fu_467_p2();
    void thread_icmp_ln39_fu_484_p2();
    void thread_icmp_ln57_fu_500_p2();
    void thread_icmp_ln62_fu_517_p2();
    void thread_icmp_ln66_fu_563_p2();
    void thread_icmp_ln82_fu_418_p2();
    void thread_j_fu_473_p2();
    void thread_max_freq_fu_556_p2();
    void thread_most_freq_fu_553_p1();
    void thread_output_V();
    void thread_output_V_ap_vld();
    void thread_p_Result_1_fu_437_p3();
    void thread_p_Result_s_fu_430_p3();
    void thread_select_ln66_1_fu_577_p3();
    void thread_select_ln66_fu_569_p3();
    void thread_select_ln83_fu_456_p3();
    void thread_sext_ln64_fu_544_p1();
    void thread_test_label_V_fu_355_p1();
    void thread_train_samples_V_address0();
    void thread_train_samples_V_ce0();
    void thread_xor_ln968_fu_444_p2();
    void thread_zext_ln27_fu_381_p1();
    void thread_zext_ln34_fu_399_p1();
    void thread_zext_ln39_fu_479_p1();
    void thread_zext_ln45_fu_490_p1();
    void thread_zext_ln58_fu_512_p1();
    void thread_zext_ln64_fu_529_p1();
    void thread_zext_ln65_fu_548_p1();
    void thread_zext_ln73_fu_534_p1();
    void thread_zext_ln82_fu_414_p1();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
