#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("k", 32, hls_in, 0, "ap_none", "in_data", 1),
	Port_Property("test_samples_label_address0", 14, hls_out, 1, "ap_memory", "mem_address", 1),
	Port_Property("test_samples_label_ce0", 1, hls_out, 1, "ap_memory", "mem_ce", 1),
	Port_Property("test_samples_label_q0", 8, hls_in, 1, "ap_memory", "mem_dout", 1),
	Port_Property("test_samples_data_address0", 20, hls_out, 2, "ap_memory", "mem_address", 1),
	Port_Property("test_samples_data_ce0", 1, hls_out, 2, "ap_memory", "mem_ce", 1),
	Port_Property("test_samples_data_q0", 8, hls_in, 2, "ap_memory", "mem_dout", 1),
	Port_Property("test_samples_data_address1", 20, hls_out, 2, "ap_memory", "MemPortADDR2", 1),
	Port_Property("test_samples_data_ce1", 1, hls_out, 2, "ap_memory", "MemPortCE2", 1),
	Port_Property("test_samples_data_q1", 8, hls_in, 2, "ap_memory", "MemPortDOUT2", 1),
	Port_Property("train_samples_label_address0", 16, hls_out, 3, "ap_memory", "mem_address", 1),
	Port_Property("train_samples_label_ce0", 1, hls_out, 3, "ap_memory", "mem_ce", 1),
	Port_Property("train_samples_label_q0", 8, hls_in, 3, "ap_memory", "mem_dout", 1),
	Port_Property("train_samples_data_address0", 23, hls_out, 4, "ap_memory", "mem_address", 1),
	Port_Property("train_samples_data_ce0", 1, hls_out, 4, "ap_memory", "mem_ce", 1),
	Port_Property("train_samples_data_q0", 8, hls_in, 4, "ap_memory", "mem_dout", 1),
	Port_Property("train_samples_data_address1", 23, hls_out, 4, "ap_memory", "MemPortADDR2", 1),
	Port_Property("train_samples_data_ce1", 1, hls_out, 4, "ap_memory", "MemPortCE2", 1),
	Port_Property("train_samples_data_q1", 8, hls_in, 4, "ap_memory", "MemPortDOUT2", 1),
	Port_Property("ap_return", 32, hls_out, -1, "", "", 1),
};
const char* HLS_Design_Meta::dut_name = "knn";
