// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "merge.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic merge::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic merge::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<12> merge::ap_ST_fsm_state1 = "1";
const sc_lv<12> merge::ap_ST_fsm_state2 = "10";
const sc_lv<12> merge::ap_ST_fsm_state3 = "100";
const sc_lv<12> merge::ap_ST_fsm_state4 = "1000";
const sc_lv<12> merge::ap_ST_fsm_state5 = "10000";
const sc_lv<12> merge::ap_ST_fsm_state6 = "100000";
const sc_lv<12> merge::ap_ST_fsm_state7 = "1000000";
const sc_lv<12> merge::ap_ST_fsm_state8 = "10000000";
const sc_lv<12> merge::ap_ST_fsm_state9 = "100000000";
const sc_lv<12> merge::ap_ST_fsm_state10 = "1000000000";
const sc_lv<12> merge::ap_ST_fsm_state11 = "10000000000";
const sc_lv<12> merge::ap_ST_fsm_state12 = "100000000000";
const sc_lv<32> merge::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> merge::ap_const_lv32_1 = "1";
const sc_lv<1> merge::ap_const_lv1_1 = "1";
const sc_lv<32> merge::ap_const_lv32_3 = "11";
const sc_lv<32> merge::ap_const_lv32_5 = "101";
const sc_lv<1> merge::ap_const_lv1_0 = "0";
const sc_lv<32> merge::ap_const_lv32_6 = "110";
const sc_lv<32> merge::ap_const_lv32_7 = "111";
const sc_lv<32> merge::ap_const_lv32_8 = "1000";
const sc_lv<32> merge::ap_const_lv32_9 = "1001";
const sc_lv<32> merge::ap_const_lv32_A = "1010";
const sc_lv<32> merge::ap_const_lv32_B = "1011";
const sc_lv<31> merge::ap_const_lv31_0 = "0000000000000000000000000000000";
const sc_lv<32> merge::ap_const_lv32_2 = "10";
const sc_lv<32> merge::ap_const_lv32_4 = "100";
const sc_lv<31> merge::ap_const_lv31_1 = "1";
const bool merge::ap_const_boolean_1 = true;

merge::merge(sc_module_name name) : sc_module(name), mVcdFile(0) {
    L_0_U = new merge_L_0("L_0_U");
    L_0_U->clk(ap_clk);
    L_0_U->reset(ap_rst);
    L_0_U->address0(L_0_address0);
    L_0_U->ce0(L_0_ce0);
    L_0_U->we0(L_0_we0);
    L_0_U->d0(arr_0_q0);
    L_0_U->q0(L_0_q0);
    L_1_U = new merge_L_0("L_1_U");
    L_1_U->clk(ap_clk);
    L_1_U->reset(ap_rst);
    L_1_U->address0(L_1_address0);
    L_1_U->ce0(L_1_ce0);
    L_1_U->we0(L_1_we0);
    L_1_U->d0(arr_1_q0);
    L_1_U->q0(L_1_q0);
    R_0_U = new merge_L_0("R_0_U");
    R_0_U->clk(ap_clk);
    R_0_U->reset(ap_rst);
    R_0_U->address0(R_0_address0);
    R_0_U->ce0(R_0_ce0);
    R_0_U->we0(R_0_we0);
    R_0_U->d0(arr_0_q0);
    R_0_U->q0(R_0_q0);
    R_1_U = new merge_L_0("R_1_U");
    R_1_U->clk(ap_clk);
    R_1_U->reset(ap_rst);
    R_1_U->address0(R_1_address0);
    R_1_U->ce0(R_1_ce0);
    R_1_U->we0(R_1_we0);
    R_1_U->d0(arr_1_q0);
    R_1_U->q0(R_1_q0);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_L_0_address0);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( sext_ln71_fu_479_p1 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( zext_ln54_fu_405_p1 );
    sensitive << ( sext_ln90_fu_567_p1 );

    SC_METHOD(thread_L_0_ce0);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_L_0_we0);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_L_1_address0);
    sensitive << ( sext_ln71_reg_712 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( zext_ln54_fu_405_p1 );
    sensitive << ( sext_ln90_fu_567_p1 );

    SC_METHOD(thread_L_1_ce0);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_L_1_we0);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_R_0_address0);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( sext_ln71_1_fu_484_p1 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( zext_ln60_fu_451_p1 );
    sensitive << ( sext_ln100_fu_596_p1 );

    SC_METHOD(thread_R_0_ce0);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_R_0_we0);
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_R_1_address0);
    sensitive << ( sext_ln71_1_reg_722 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( zext_ln60_fu_451_p1 );
    sensitive << ( sext_ln100_fu_596_p1 );

    SC_METHOD(thread_R_1_ce0);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_R_1_we0);
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_add_ln54_fu_394_p2);
    sensitive << ( l );
    sensitive << ( zext_ln52_fu_379_p1 );

    SC_METHOD(thread_add_ln60_1_fu_430_p2);
    sensitive << ( m );
    sensitive << ( zext_ln60_1_fu_426_p1 );

    SC_METHOD(thread_add_ln84_fu_556_p2);
    sensitive << ( indvars_iv_reg_312 );

    SC_METHOD(thread_add_ln88_fu_494_p2);
    sensitive << ( m );
    sensitive << ( sub_ln88_fu_489_p2 );

    SC_METHOD(thread_and_ln69_fu_473_p2);
    sensitive << ( icmp_ln69_fu_463_p2 );
    sensitive << ( icmp_ln69_1_fu_468_p2 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state12);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( icmp_ln98_fu_591_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( icmp_ln98_fu_591_p2 );

    SC_METHOD(thread_arr_0_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( icmp_ln71_fu_525_p2 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( sext_ln79_fu_531_p1 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( sext_ln54_fu_399_p1 );
    sensitive << ( sext_ln60_fu_435_p1 );
    sensitive << ( sext_ln90_1_fu_579_p1 );
    sensitive << ( sext_ln100_1_fu_608_p1 );

    SC_METHOD(thread_arr_0_ce0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( icmp_ln71_fu_525_p2 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state12 );

    SC_METHOD(thread_arr_0_d0);
    sensitive << ( icmp_ln71_fu_525_p2 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( L_0_q0 );
    sensitive << ( R_0_q0 );

    SC_METHOD(thread_arr_0_we0);
    sensitive << ( icmp_ln71_fu_525_p2 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state12 );

    SC_METHOD(thread_arr_1_addr_2_gep_fu_219_p3);
    sensitive << ( icmp_ln71_reg_737 );
    sensitive << ( sext_ln79_reg_741 );
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_arr_1_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( icmp_ln71_reg_737 );
    sensitive << ( sext_ln79_reg_741 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( sext_ln54_fu_399_p1 );
    sensitive << ( sext_ln60_fu_435_p1 );
    sensitive << ( arr_1_addr_2_gep_fu_219_p3 );
    sensitive << ( sext_ln90_1_fu_579_p1 );
    sensitive << ( sext_ln100_1_fu_608_p1 );

    SC_METHOD(thread_arr_1_ce0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( icmp_ln71_reg_737 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state12 );

    SC_METHOD(thread_arr_1_d0);
    sensitive << ( icmp_ln71_reg_737 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( L_1_q0 );
    sensitive << ( R_1_q0 );

    SC_METHOD(thread_arr_1_we0);
    sensitive << ( icmp_ln71_reg_737 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state12 );

    SC_METHOD(thread_empty_fu_499_p0);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( i_1_fu_56 );

    SC_METHOD(thread_empty_fu_499_p2);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( and_ln69_fu_473_p2 );
    sensitive << ( empty_fu_499_p0 );
    sensitive << ( add_ln88_fu_494_p2 );

    SC_METHOD(thread_i_2_fu_536_p2);
    sensitive << ( i_1_load_reg_703 );

    SC_METHOD(thread_i_4_fu_573_p2);
    sensitive << ( i_3_reg_322 );

    SC_METHOD(thread_i_fu_388_p2);
    sensitive << ( i_0_reg_288 );

    SC_METHOD(thread_icmp_ln52_fu_383_p2);
    sensitive << ( n1_reg_633 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( zext_ln52_fu_379_p1 );

    SC_METHOD(thread_icmp_ln58_fu_415_p2);
    sensitive << ( n2_reg_640 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( zext_ln58_fu_411_p1 );

    SC_METHOD(thread_icmp_ln69_1_fu_468_p0);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( j_1_fu_52 );

    SC_METHOD(thread_icmp_ln69_1_fu_468_p2);
    sensitive << ( n2_reg_640 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( icmp_ln69_1_fu_468_p0 );

    SC_METHOD(thread_icmp_ln69_fu_463_p0);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( i_1_fu_56 );

    SC_METHOD(thread_icmp_ln69_fu_463_p2);
    sensitive << ( n1_reg_633 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( icmp_ln69_fu_463_p0 );

    SC_METHOD(thread_icmp_ln71_fu_525_p2);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( L_0_q0 );
    sensitive << ( R_0_q0 );

    SC_METHOD(thread_icmp_ln88_fu_562_p2);
    sensitive << ( n1_reg_633 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( i_3_reg_322 );

    SC_METHOD(thread_icmp_ln98_fu_591_p2);
    sensitive << ( n2_reg_640 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( j_3_reg_342 );

    SC_METHOD(thread_j_2_fu_546_p2);
    sensitive << ( j_1_load_reg_697 );

    SC_METHOD(thread_j_4_fu_602_p2);
    sensitive << ( j_3_reg_342 );

    SC_METHOD(thread_j_fu_420_p2);
    sensitive << ( j_0_reg_300 );

    SC_METHOD(thread_k_3_fu_585_p2);
    sensitive << ( k_1_reg_331 );

    SC_METHOD(thread_k_4_fu_614_p2);
    sensitive << ( k_2_reg_351 );

    SC_METHOD(thread_k_fu_519_p2);
    sensitive << ( sub_ln88_1_fu_513_p2 );
    sensitive << ( smax_fu_505_p3 );

    SC_METHOD(thread_n1_fu_367_p2);
    sensitive << ( sub_ln44_fu_361_p2 );

    SC_METHOD(thread_n2_fu_373_p2);
    sensitive << ( m );
    sensitive << ( r );

    SC_METHOD(thread_sext_ln100_1_fu_608_p1);
    sensitive << ( k_2_reg_351 );

    SC_METHOD(thread_sext_ln100_fu_596_p1);
    sensitive << ( j_3_reg_342 );

    SC_METHOD(thread_sext_ln54_fu_399_p1);
    sensitive << ( add_ln54_fu_394_p2 );

    SC_METHOD(thread_sext_ln60_fu_435_p1);
    sensitive << ( add_ln60_1_fu_430_p2 );

    SC_METHOD(thread_sext_ln71_1_fu_484_p0);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( j_1_fu_52 );

    SC_METHOD(thread_sext_ln71_1_fu_484_p1);
    sensitive << ( sext_ln71_1_fu_484_p0 );

    SC_METHOD(thread_sext_ln71_fu_479_p0);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( i_1_fu_56 );

    SC_METHOD(thread_sext_ln71_fu_479_p1);
    sensitive << ( sext_ln71_fu_479_p0 );

    SC_METHOD(thread_sext_ln79_fu_531_p1);
    sensitive << ( indvars_iv_reg_312 );

    SC_METHOD(thread_sext_ln90_1_fu_579_p1);
    sensitive << ( k_1_reg_331 );

    SC_METHOD(thread_sext_ln90_fu_567_p1);
    sensitive << ( i_3_reg_322 );

    SC_METHOD(thread_smax_fu_505_p1);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( i_1_fu_56 );

    SC_METHOD(thread_smax_fu_505_p3);
    sensitive << ( add_ln88_fu_494_p2 );
    sensitive << ( empty_fu_499_p2 );
    sensitive << ( smax_fu_505_p1 );

    SC_METHOD(thread_sub_ln44_fu_361_p2);
    sensitive << ( l );
    sensitive << ( m );

    SC_METHOD(thread_sub_ln88_1_fu_513_p1);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( i_1_fu_56 );

    SC_METHOD(thread_sub_ln88_1_fu_513_p2);
    sensitive << ( indvars_iv_reg_312 );
    sensitive << ( sub_ln88_1_fu_513_p1 );

    SC_METHOD(thread_sub_ln88_fu_489_p2);
    sensitive << ( l );

    SC_METHOD(thread_zext_ln52_fu_379_p1);
    sensitive << ( i_0_reg_288 );

    SC_METHOD(thread_zext_ln54_fu_405_p1);
    sensitive << ( i_0_reg_288 );

    SC_METHOD(thread_zext_ln58_fu_411_p1);
    sensitive << ( j_0_reg_300 );

    SC_METHOD(thread_zext_ln60_1_fu_426_p1);
    sensitive << ( j_fu_420_p2 );

    SC_METHOD(thread_zext_ln60_fu_451_p1);
    sensitive << ( j_0_reg_300 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln52_fu_383_p2 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( icmp_ln58_fu_415_p2 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( and_ln69_fu_473_p2 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( icmp_ln88_fu_562_p2 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( icmp_ln98_fu_591_p2 );

    ap_CS_fsm = "000000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "merge_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, arr_0_address0, "(port)arr_0_address0");
    sc_trace(mVcdFile, arr_0_ce0, "(port)arr_0_ce0");
    sc_trace(mVcdFile, arr_0_we0, "(port)arr_0_we0");
    sc_trace(mVcdFile, arr_0_d0, "(port)arr_0_d0");
    sc_trace(mVcdFile, arr_0_q0, "(port)arr_0_q0");
    sc_trace(mVcdFile, arr_1_address0, "(port)arr_1_address0");
    sc_trace(mVcdFile, arr_1_ce0, "(port)arr_1_ce0");
    sc_trace(mVcdFile, arr_1_we0, "(port)arr_1_we0");
    sc_trace(mVcdFile, arr_1_d0, "(port)arr_1_d0");
    sc_trace(mVcdFile, arr_1_q0, "(port)arr_1_q0");
    sc_trace(mVcdFile, l, "(port)l");
    sc_trace(mVcdFile, m, "(port)m");
    sc_trace(mVcdFile, r, "(port)r");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, n1_fu_367_p2, "n1_fu_367_p2");
    sc_trace(mVcdFile, n1_reg_633, "n1_reg_633");
    sc_trace(mVcdFile, n2_fu_373_p2, "n2_fu_373_p2");
    sc_trace(mVcdFile, n2_reg_640, "n2_reg_640");
    sc_trace(mVcdFile, i_fu_388_p2, "i_fu_388_p2");
    sc_trace(mVcdFile, i_reg_650, "i_reg_650");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, icmp_ln52_fu_383_p2, "icmp_ln52_fu_383_p2");
    sc_trace(mVcdFile, j_fu_420_p2, "j_fu_420_p2");
    sc_trace(mVcdFile, j_reg_668, "j_reg_668");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, icmp_ln58_fu_415_p2, "icmp_ln58_fu_415_p2");
    sc_trace(mVcdFile, j_1_load_reg_697, "j_1_load_reg_697");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, i_1_load_reg_703, "i_1_load_reg_703");
    sc_trace(mVcdFile, sext_ln71_fu_479_p1, "sext_ln71_fu_479_p1");
    sc_trace(mVcdFile, sext_ln71_reg_712, "sext_ln71_reg_712");
    sc_trace(mVcdFile, and_ln69_fu_473_p2, "and_ln69_fu_473_p2");
    sc_trace(mVcdFile, sext_ln71_1_fu_484_p1, "sext_ln71_1_fu_484_p1");
    sc_trace(mVcdFile, sext_ln71_1_reg_722, "sext_ln71_1_reg_722");
    sc_trace(mVcdFile, k_fu_519_p2, "k_fu_519_p2");
    sc_trace(mVcdFile, k_reg_732, "k_reg_732");
    sc_trace(mVcdFile, icmp_ln71_fu_525_p2, "icmp_ln71_fu_525_p2");
    sc_trace(mVcdFile, icmp_ln71_reg_737, "icmp_ln71_reg_737");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, sext_ln79_fu_531_p1, "sext_ln79_fu_531_p1");
    sc_trace(mVcdFile, sext_ln79_reg_741, "sext_ln79_reg_741");
    sc_trace(mVcdFile, add_ln84_fu_556_p2, "add_ln84_fu_556_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, icmp_ln88_fu_562_p2, "icmp_ln88_fu_562_p2");
    sc_trace(mVcdFile, i_4_fu_573_p2, "i_4_fu_573_p2");
    sc_trace(mVcdFile, i_4_reg_775, "i_4_reg_775");
    sc_trace(mVcdFile, k_3_fu_585_p2, "k_3_fu_585_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, icmp_ln98_fu_591_p2, "icmp_ln98_fu_591_p2");
    sc_trace(mVcdFile, j_4_fu_602_p2, "j_4_fu_602_p2");
    sc_trace(mVcdFile, j_4_reg_798, "j_4_reg_798");
    sc_trace(mVcdFile, k_4_fu_614_p2, "k_4_fu_614_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state12, "ap_CS_fsm_state12");
    sc_trace(mVcdFile, L_0_address0, "L_0_address0");
    sc_trace(mVcdFile, L_0_ce0, "L_0_ce0");
    sc_trace(mVcdFile, L_0_we0, "L_0_we0");
    sc_trace(mVcdFile, L_0_q0, "L_0_q0");
    sc_trace(mVcdFile, L_1_address0, "L_1_address0");
    sc_trace(mVcdFile, L_1_ce0, "L_1_ce0");
    sc_trace(mVcdFile, L_1_we0, "L_1_we0");
    sc_trace(mVcdFile, L_1_q0, "L_1_q0");
    sc_trace(mVcdFile, R_0_address0, "R_0_address0");
    sc_trace(mVcdFile, R_0_ce0, "R_0_ce0");
    sc_trace(mVcdFile, R_0_we0, "R_0_we0");
    sc_trace(mVcdFile, R_0_q0, "R_0_q0");
    sc_trace(mVcdFile, R_1_address0, "R_1_address0");
    sc_trace(mVcdFile, R_1_ce0, "R_1_ce0");
    sc_trace(mVcdFile, R_1_we0, "R_1_we0");
    sc_trace(mVcdFile, R_1_q0, "R_1_q0");
    sc_trace(mVcdFile, i_0_reg_288, "i_0_reg_288");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, j_0_reg_300, "j_0_reg_300");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, indvars_iv_reg_312, "indvars_iv_reg_312");
    sc_trace(mVcdFile, i_3_reg_322, "i_3_reg_322");
    sc_trace(mVcdFile, k_1_reg_331, "k_1_reg_331");
    sc_trace(mVcdFile, j_3_reg_342, "j_3_reg_342");
    sc_trace(mVcdFile, k_2_reg_351, "k_2_reg_351");
    sc_trace(mVcdFile, sext_ln54_fu_399_p1, "sext_ln54_fu_399_p1");
    sc_trace(mVcdFile, zext_ln54_fu_405_p1, "zext_ln54_fu_405_p1");
    sc_trace(mVcdFile, sext_ln60_fu_435_p1, "sext_ln60_fu_435_p1");
    sc_trace(mVcdFile, zext_ln60_fu_451_p1, "zext_ln60_fu_451_p1");
    sc_trace(mVcdFile, arr_1_addr_2_gep_fu_219_p3, "arr_1_addr_2_gep_fu_219_p3");
    sc_trace(mVcdFile, sext_ln90_fu_567_p1, "sext_ln90_fu_567_p1");
    sc_trace(mVcdFile, sext_ln90_1_fu_579_p1, "sext_ln90_1_fu_579_p1");
    sc_trace(mVcdFile, sext_ln100_fu_596_p1, "sext_ln100_fu_596_p1");
    sc_trace(mVcdFile, sext_ln100_1_fu_608_p1, "sext_ln100_1_fu_608_p1");
    sc_trace(mVcdFile, j_1_fu_52, "j_1_fu_52");
    sc_trace(mVcdFile, j_2_fu_546_p2, "j_2_fu_546_p2");
    sc_trace(mVcdFile, i_1_fu_56, "i_1_fu_56");
    sc_trace(mVcdFile, i_2_fu_536_p2, "i_2_fu_536_p2");
    sc_trace(mVcdFile, sub_ln44_fu_361_p2, "sub_ln44_fu_361_p2");
    sc_trace(mVcdFile, zext_ln52_fu_379_p1, "zext_ln52_fu_379_p1");
    sc_trace(mVcdFile, add_ln54_fu_394_p2, "add_ln54_fu_394_p2");
    sc_trace(mVcdFile, zext_ln58_fu_411_p1, "zext_ln58_fu_411_p1");
    sc_trace(mVcdFile, zext_ln60_1_fu_426_p1, "zext_ln60_1_fu_426_p1");
    sc_trace(mVcdFile, add_ln60_1_fu_430_p2, "add_ln60_1_fu_430_p2");
    sc_trace(mVcdFile, icmp_ln69_fu_463_p0, "icmp_ln69_fu_463_p0");
    sc_trace(mVcdFile, icmp_ln69_1_fu_468_p0, "icmp_ln69_1_fu_468_p0");
    sc_trace(mVcdFile, icmp_ln69_fu_463_p2, "icmp_ln69_fu_463_p2");
    sc_trace(mVcdFile, icmp_ln69_1_fu_468_p2, "icmp_ln69_1_fu_468_p2");
    sc_trace(mVcdFile, sext_ln71_fu_479_p0, "sext_ln71_fu_479_p0");
    sc_trace(mVcdFile, sext_ln71_1_fu_484_p0, "sext_ln71_1_fu_484_p0");
    sc_trace(mVcdFile, sub_ln88_fu_489_p2, "sub_ln88_fu_489_p2");
    sc_trace(mVcdFile, empty_fu_499_p0, "empty_fu_499_p0");
    sc_trace(mVcdFile, add_ln88_fu_494_p2, "add_ln88_fu_494_p2");
    sc_trace(mVcdFile, empty_fu_499_p2, "empty_fu_499_p2");
    sc_trace(mVcdFile, smax_fu_505_p1, "smax_fu_505_p1");
    sc_trace(mVcdFile, sub_ln88_1_fu_513_p1, "sub_ln88_1_fu_513_p1");
    sc_trace(mVcdFile, sub_ln88_1_fu_513_p2, "sub_ln88_1_fu_513_p2");
    sc_trace(mVcdFile, smax_fu_505_p3, "smax_fu_505_p3");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

merge::~merge() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete L_0_U;
    delete L_1_U;
    delete R_0_U;
    delete R_1_U;
}

void merge::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        i_0_reg_288 = i_reg_650.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        i_0_reg_288 = ap_const_lv31_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln71_fu_525_p2.read()))) {
        i_1_fu_56 = i_2_fu_536_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                esl_seteq<1,1,1>(icmp_ln58_fu_415_p2.read(), ap_const_lv1_0))) {
        i_1_fu_56 = ap_const_lv32_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        i_3_reg_322 = i_4_reg_775.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
                esl_seteq<1,1,1>(and_ln69_fu_473_p2.read(), ap_const_lv1_0))) {
        i_3_reg_322 = i_1_fu_56.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(icmp_ln58_fu_415_p2.read(), ap_const_lv1_0))) {
        indvars_iv_reg_312 = l.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        indvars_iv_reg_312 = add_ln84_fu_556_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln52_fu_383_p2.read(), ap_const_lv1_0))) {
        j_0_reg_300 = ap_const_lv31_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        j_0_reg_300 = j_reg_668.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln71_reg_737.read()))) {
        j_1_fu_52 = j_2_fu_546_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                esl_seteq<1,1,1>(icmp_ln58_fu_415_p2.read(), ap_const_lv1_0))) {
        j_1_fu_52 = ap_const_lv32_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln88_fu_562_p2.read()))) {
        j_3_reg_342 = j_1_load_reg_697.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        j_3_reg_342 = j_4_reg_798.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        k_1_reg_331 = k_3_fu_585_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
                esl_seteq<1,1,1>(and_ln69_fu_473_p2.read(), ap_const_lv1_0))) {
        k_1_reg_331 = indvars_iv_reg_312.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln88_fu_562_p2.read()))) {
        k_2_reg_351 = k_reg_732.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        k_2_reg_351 = k_4_fu_614_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        i_1_load_reg_703 = i_1_fu_56.read();
        j_1_load_reg_697 = j_1_fu_52.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln88_fu_562_p2.read()))) {
        i_4_reg_775 = i_4_fu_573_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        i_reg_650 = i_fu_388_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        icmp_ln71_reg_737 = icmp_ln71_fu_525_p2.read();
        sext_ln79_reg_741 = sext_ln79_fu_531_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln98_fu_591_p2.read()))) {
        j_4_reg_798 = j_4_fu_602_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        j_reg_668 = j_fu_420_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(and_ln69_fu_473_p2.read(), ap_const_lv1_0))) {
        k_reg_732 = k_fu_519_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        n1_reg_633 = n1_fu_367_p2.read();
        n2_reg_640 = n2_fu_373_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, and_ln69_fu_473_p2.read()))) {
        sext_ln71_1_reg_722 = sext_ln71_1_fu_484_p1.read();
        sext_ln71_reg_712 = sext_ln71_fu_479_p1.read();
    }
}

void merge::thread_L_0_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        L_0_address0 =  (sc_lv<16>) (sext_ln90_fu_567_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        L_0_address0 =  (sc_lv<16>) (sext_ln71_fu_479_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        L_0_address0 =  (sc_lv<16>) (zext_ln54_fu_405_p1.read());
    } else {
        L_0_address0 = "XXXXXXXXXXXXXXXX";
    }
}

void merge::thread_L_0_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()))) {
        L_0_ce0 = ap_const_logic_1;
    } else {
        L_0_ce0 = ap_const_logic_0;
    }
}

void merge::thread_L_0_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        L_0_we0 = ap_const_logic_1;
    } else {
        L_0_we0 = ap_const_logic_0;
    }
}

void merge::thread_L_1_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        L_1_address0 =  (sc_lv<16>) (sext_ln90_fu_567_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        L_1_address0 =  (sc_lv<16>) (sext_ln71_reg_712.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        L_1_address0 =  (sc_lv<16>) (zext_ln54_fu_405_p1.read());
    } else {
        L_1_address0 = "XXXXXXXXXXXXXXXX";
    }
}

void merge::thread_L_1_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()))) {
        L_1_ce0 = ap_const_logic_1;
    } else {
        L_1_ce0 = ap_const_logic_0;
    }
}

void merge::thread_L_1_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        L_1_we0 = ap_const_logic_1;
    } else {
        L_1_we0 = ap_const_logic_0;
    }
}

void merge::thread_R_0_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        R_0_address0 =  (sc_lv<16>) (sext_ln100_fu_596_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        R_0_address0 =  (sc_lv<16>) (sext_ln71_1_fu_484_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        R_0_address0 =  (sc_lv<16>) (zext_ln60_fu_451_p1.read());
    } else {
        R_0_address0 = "XXXXXXXXXXXXXXXX";
    }
}

void merge::thread_R_0_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()))) {
        R_0_ce0 = ap_const_logic_1;
    } else {
        R_0_ce0 = ap_const_logic_0;
    }
}

void merge::thread_R_0_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        R_0_we0 = ap_const_logic_1;
    } else {
        R_0_we0 = ap_const_logic_0;
    }
}

void merge::thread_R_1_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        R_1_address0 =  (sc_lv<16>) (sext_ln100_fu_596_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        R_1_address0 =  (sc_lv<16>) (sext_ln71_1_reg_722.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        R_1_address0 =  (sc_lv<16>) (zext_ln60_fu_451_p1.read());
    } else {
        R_1_address0 = "XXXXXXXXXXXXXXXX";
    }
}

void merge::thread_R_1_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()))) {
        R_1_ce0 = ap_const_logic_1;
    } else {
        R_1_ce0 = ap_const_logic_0;
    }
}

void merge::thread_R_1_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        R_1_we0 = ap_const_logic_1;
    } else {
        R_1_we0 = ap_const_logic_0;
    }
}

void merge::thread_add_ln54_fu_394_p2() {
    add_ln54_fu_394_p2 = (!zext_ln52_fu_379_p1.read().is_01() || !l.read().is_01())? sc_lv<32>(): (sc_biguint<32>(zext_ln52_fu_379_p1.read()) + sc_biguint<32>(l.read()));
}

void merge::thread_add_ln60_1_fu_430_p2() {
    add_ln60_1_fu_430_p2 = (!zext_ln60_1_fu_426_p1.read().is_01() || !m.read().is_01())? sc_lv<32>(): (sc_biguint<32>(zext_ln60_1_fu_426_p1.read()) + sc_biguint<32>(m.read()));
}

void merge::thread_add_ln84_fu_556_p2() {
    add_ln84_fu_556_p2 = (!indvars_iv_reg_312.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_bigint<32>(indvars_iv_reg_312.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void merge::thread_add_ln88_fu_494_p2() {
    add_ln88_fu_494_p2 = (!sub_ln88_fu_489_p2.read().is_01() || !m.read().is_01())? sc_lv<32>(): (sc_biguint<32>(sub_ln88_fu_489_p2.read()) + sc_biguint<32>(m.read()));
}

void merge::thread_and_ln69_fu_473_p2() {
    and_ln69_fu_473_p2 = (icmp_ln69_fu_463_p2.read() & icmp_ln69_1_fu_468_p2.read());
}

void merge::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void merge::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[9];
}

void merge::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read()[10];
}

void merge::thread_ap_CS_fsm_state12() {
    ap_CS_fsm_state12 = ap_CS_fsm.read()[11];
}

void merge::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void merge::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void merge::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void merge::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void merge::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void merge::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void merge::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void merge::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void merge::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln98_fu_591_p2.read())))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void merge::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void merge::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln98_fu_591_p2.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void merge::thread_arr_0_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        arr_0_address0 =  (sc_lv<16>) (sext_ln100_1_fu_608_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        arr_0_address0 =  (sc_lv<16>) (sext_ln90_1_fu_579_p1.read());
    } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln71_fu_525_p2.read())) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln71_fu_525_p2.read())))) {
        arr_0_address0 =  (sc_lv<16>) (sext_ln79_fu_531_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        arr_0_address0 =  (sc_lv<16>) (sext_ln60_fu_435_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        arr_0_address0 =  (sc_lv<16>) (sext_ln54_fu_399_p1.read());
    } else {
        arr_0_address0 = "XXXXXXXXXXXXXXXX";
    }
}

void merge::thread_arr_0_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln71_fu_525_p2.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln71_fu_525_p2.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()))) {
        arr_0_ce0 = ap_const_logic_1;
    } else {
        arr_0_ce0 = ap_const_logic_0;
    }
}

void merge::thread_arr_0_d0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln71_fu_525_p2.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()))) {
        arr_0_d0 = R_0_q0.read();
    } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln71_fu_525_p2.read())) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()))) {
        arr_0_d0 = L_0_q0.read();
    } else {
        arr_0_d0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void merge::thread_arr_0_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln71_fu_525_p2.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln71_fu_525_p2.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()))) {
        arr_0_we0 = ap_const_logic_1;
    } else {
        arr_0_we0 = ap_const_logic_0;
    }
}

void merge::thread_arr_1_addr_2_gep_fu_219_p3() {
    arr_1_addr_2_gep_fu_219_p3 =  (sc_lv<16>) (sext_ln79_reg_741.read());
}

void merge::thread_arr_1_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        arr_1_address0 =  (sc_lv<16>) (sext_ln100_1_fu_608_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        arr_1_address0 =  (sc_lv<16>) (sext_ln90_1_fu_579_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln71_reg_737.read()))) {
        arr_1_address0 = arr_1_addr_2_gep_fu_219_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln71_reg_737.read()))) {
        arr_1_address0 =  (sc_lv<16>) (sext_ln79_reg_741.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        arr_1_address0 =  (sc_lv<16>) (sext_ln60_fu_435_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        arr_1_address0 =  (sc_lv<16>) (sext_ln54_fu_399_p1.read());
    } else {
        arr_1_address0 = "XXXXXXXXXXXXXXXX";
    }
}

void merge::thread_arr_1_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln71_reg_737.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln71_reg_737.read())))) {
        arr_1_ce0 = ap_const_logic_1;
    } else {
        arr_1_ce0 = ap_const_logic_0;
    }
}

void merge::thread_arr_1_d0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln71_reg_737.read())))) {
        arr_1_d0 = R_1_q0.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln71_reg_737.read())))) {
        arr_1_d0 = L_1_q0.read();
    } else {
        arr_1_d0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void merge::thread_arr_1_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln71_reg_737.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln71_reg_737.read())))) {
        arr_1_we0 = ap_const_logic_1;
    } else {
        arr_1_we0 = ap_const_logic_0;
    }
}

void merge::thread_empty_fu_499_p0() {
    empty_fu_499_p0 = i_1_fu_56.read();
}

void merge::thread_empty_fu_499_p2() {
    empty_fu_499_p2 = (!empty_fu_499_p0.read().is_01() || !add_ln88_fu_494_p2.read().is_01())? sc_lv<1>(): (sc_bigint<32>(empty_fu_499_p0.read()) > sc_bigint<32>(add_ln88_fu_494_p2.read()));
}

void merge::thread_i_2_fu_536_p2() {
    i_2_fu_536_p2 = (!i_1_load_reg_703.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_bigint<32>(i_1_load_reg_703.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void merge::thread_i_4_fu_573_p2() {
    i_4_fu_573_p2 = (!i_3_reg_322.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_bigint<32>(i_3_reg_322.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void merge::thread_i_fu_388_p2() {
    i_fu_388_p2 = (!i_0_reg_288.read().is_01() || !ap_const_lv31_1.is_01())? sc_lv<31>(): (sc_biguint<31>(i_0_reg_288.read()) + sc_biguint<31>(ap_const_lv31_1));
}

void merge::thread_icmp_ln52_fu_383_p2() {
    icmp_ln52_fu_383_p2 = (!zext_ln52_fu_379_p1.read().is_01() || !n1_reg_633.read().is_01())? sc_lv<1>(): (sc_bigint<32>(zext_ln52_fu_379_p1.read()) < sc_bigint<32>(n1_reg_633.read()));
}

void merge::thread_icmp_ln58_fu_415_p2() {
    icmp_ln58_fu_415_p2 = (!zext_ln58_fu_411_p1.read().is_01() || !n2_reg_640.read().is_01())? sc_lv<1>(): (sc_bigint<32>(zext_ln58_fu_411_p1.read()) < sc_bigint<32>(n2_reg_640.read()));
}

void merge::thread_icmp_ln69_1_fu_468_p0() {
    icmp_ln69_1_fu_468_p0 = j_1_fu_52.read();
}

void merge::thread_icmp_ln69_1_fu_468_p2() {
    icmp_ln69_1_fu_468_p2 = (!icmp_ln69_1_fu_468_p0.read().is_01() || !n2_reg_640.read().is_01())? sc_lv<1>(): (sc_bigint<32>(icmp_ln69_1_fu_468_p0.read()) < sc_bigint<32>(n2_reg_640.read()));
}

void merge::thread_icmp_ln69_fu_463_p0() {
    icmp_ln69_fu_463_p0 = i_1_fu_56.read();
}

void merge::thread_icmp_ln69_fu_463_p2() {
    icmp_ln69_fu_463_p2 = (!icmp_ln69_fu_463_p0.read().is_01() || !n1_reg_633.read().is_01())? sc_lv<1>(): (sc_bigint<32>(icmp_ln69_fu_463_p0.read()) < sc_bigint<32>(n1_reg_633.read()));
}

void merge::thread_icmp_ln71_fu_525_p2() {
    icmp_ln71_fu_525_p2 = (!L_0_q0.read().is_01() || !R_0_q0.read().is_01())? sc_lv<1>(): (sc_bigint<32>(L_0_q0.read()) > sc_bigint<32>(R_0_q0.read()));
}

void merge::thread_icmp_ln88_fu_562_p2() {
    icmp_ln88_fu_562_p2 = (!i_3_reg_322.read().is_01() || !n1_reg_633.read().is_01())? sc_lv<1>(): (sc_bigint<32>(i_3_reg_322.read()) < sc_bigint<32>(n1_reg_633.read()));
}

void merge::thread_icmp_ln98_fu_591_p2() {
    icmp_ln98_fu_591_p2 = (!j_3_reg_342.read().is_01() || !n2_reg_640.read().is_01())? sc_lv<1>(): (sc_bigint<32>(j_3_reg_342.read()) < sc_bigint<32>(n2_reg_640.read()));
}

void merge::thread_j_2_fu_546_p2() {
    j_2_fu_546_p2 = (!j_1_load_reg_697.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_bigint<32>(j_1_load_reg_697.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void merge::thread_j_4_fu_602_p2() {
    j_4_fu_602_p2 = (!j_3_reg_342.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_bigint<32>(j_3_reg_342.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void merge::thread_j_fu_420_p2() {
    j_fu_420_p2 = (!j_0_reg_300.read().is_01() || !ap_const_lv31_1.is_01())? sc_lv<31>(): (sc_biguint<31>(j_0_reg_300.read()) + sc_biguint<31>(ap_const_lv31_1));
}

void merge::thread_k_3_fu_585_p2() {
    k_3_fu_585_p2 = (!k_1_reg_331.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_bigint<32>(k_1_reg_331.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void merge::thread_k_4_fu_614_p2() {
    k_4_fu_614_p2 = (!k_2_reg_351.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_bigint<32>(k_2_reg_351.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void merge::thread_k_fu_519_p2() {
    k_fu_519_p2 = (!sub_ln88_1_fu_513_p2.read().is_01() || !smax_fu_505_p3.read().is_01())? sc_lv<32>(): (sc_biguint<32>(sub_ln88_1_fu_513_p2.read()) + sc_biguint<32>(smax_fu_505_p3.read()));
}

void merge::thread_n1_fu_367_p2() {
    n1_fu_367_p2 = (!sub_ln44_fu_361_p2.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(sub_ln44_fu_361_p2.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void merge::thread_n2_fu_373_p2() {
    n2_fu_373_p2 = (!r.read().is_01() || !m.read().is_01())? sc_lv<32>(): (sc_biguint<32>(r.read()) - sc_biguint<32>(m.read()));
}

void merge::thread_sext_ln100_1_fu_608_p1() {
    sext_ln100_1_fu_608_p1 = esl_sext<64,32>(k_2_reg_351.read());
}

void merge::thread_sext_ln100_fu_596_p1() {
    sext_ln100_fu_596_p1 = esl_sext<64,32>(j_3_reg_342.read());
}

void merge::thread_sext_ln54_fu_399_p1() {
    sext_ln54_fu_399_p1 = esl_sext<64,32>(add_ln54_fu_394_p2.read());
}

void merge::thread_sext_ln60_fu_435_p1() {
    sext_ln60_fu_435_p1 = esl_sext<64,32>(add_ln60_1_fu_430_p2.read());
}

void merge::thread_sext_ln71_1_fu_484_p0() {
    sext_ln71_1_fu_484_p0 = j_1_fu_52.read();
}

void merge::thread_sext_ln71_1_fu_484_p1() {
    sext_ln71_1_fu_484_p1 = esl_sext<64,32>(sext_ln71_1_fu_484_p0.read());
}

void merge::thread_sext_ln71_fu_479_p0() {
    sext_ln71_fu_479_p0 = i_1_fu_56.read();
}

void merge::thread_sext_ln71_fu_479_p1() {
    sext_ln71_fu_479_p1 = esl_sext<64,32>(sext_ln71_fu_479_p0.read());
}

void merge::thread_sext_ln79_fu_531_p1() {
    sext_ln79_fu_531_p1 = esl_sext<64,32>(indvars_iv_reg_312.read());
}

void merge::thread_sext_ln90_1_fu_579_p1() {
    sext_ln90_1_fu_579_p1 = esl_sext<64,32>(k_1_reg_331.read());
}

void merge::thread_sext_ln90_fu_567_p1() {
    sext_ln90_fu_567_p1 = esl_sext<64,32>(i_3_reg_322.read());
}

void merge::thread_smax_fu_505_p1() {
    smax_fu_505_p1 = i_1_fu_56.read();
}

void merge::thread_smax_fu_505_p3() {
    smax_fu_505_p3 = (!empty_fu_499_p2.read()[0].is_01())? sc_lv<32>(): ((empty_fu_499_p2.read()[0].to_bool())? smax_fu_505_p1.read(): add_ln88_fu_494_p2.read());
}

void merge::thread_sub_ln44_fu_361_p2() {
    sub_ln44_fu_361_p2 = (!m.read().is_01() || !l.read().is_01())? sc_lv<32>(): (sc_biguint<32>(m.read()) - sc_biguint<32>(l.read()));
}

void merge::thread_sub_ln88_1_fu_513_p1() {
    sub_ln88_1_fu_513_p1 = i_1_fu_56.read();
}

void merge::thread_sub_ln88_1_fu_513_p2() {
    sub_ln88_1_fu_513_p2 = (!indvars_iv_reg_312.read().is_01() || !sub_ln88_1_fu_513_p1.read().is_01())? sc_lv<32>(): (sc_bigint<32>(indvars_iv_reg_312.read()) - sc_bigint<32>(sub_ln88_1_fu_513_p1.read()));
}

void merge::thread_sub_ln88_fu_489_p2() {
    sub_ln88_fu_489_p2 = (!ap_const_lv32_1.is_01() || !l.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_1) - sc_biguint<32>(l.read()));
}

void merge::thread_zext_ln52_fu_379_p1() {
    zext_ln52_fu_379_p1 = esl_zext<32,31>(i_0_reg_288.read());
}

void merge::thread_zext_ln54_fu_405_p1() {
    zext_ln54_fu_405_p1 = esl_zext<64,31>(i_0_reg_288.read());
}

void merge::thread_zext_ln58_fu_411_p1() {
    zext_ln58_fu_411_p1 = esl_zext<32,31>(j_0_reg_300.read());
}

void merge::thread_zext_ln60_1_fu_426_p1() {
    zext_ln60_1_fu_426_p1 = esl_zext<32,31>(j_fu_420_p2.read());
}

void merge::thread_zext_ln60_fu_451_p1() {
    zext_ln60_fu_451_p1 = esl_zext<64,31>(j_0_reg_300.read());
}

void merge::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln52_fu_383_p2.read(), ap_const_lv1_0))) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state2;
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(icmp_ln58_fu_415_p2.read(), ap_const_lv1_0))) {
                ap_NS_fsm = ap_ST_fsm_state6;
            } else {
                ap_NS_fsm = ap_ST_fsm_state5;
            }
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 32 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(and_ln69_fu_473_p2.read(), ap_const_lv1_0))) {
                ap_NS_fsm = ap_ST_fsm_state9;
            } else {
                ap_NS_fsm = ap_ST_fsm_state7;
            }
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 256 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln88_fu_562_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state11;
            } else {
                ap_NS_fsm = ap_ST_fsm_state10;
            }
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 1024 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln98_fu_591_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state12;
            }
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_fsm_state11;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<12>) ("XXXXXXXXXXXX");
            break;
    }
}

}

